print ('Name : Abdulkabir Omeiza Abdulmalik')
print ('E-mail: abdulmaleekabdulkabir2017@gmail.com')
print ('Language used: python')
print ('Biostack: Data analytics')
print ('Slack username: @kaybee')
