print ('NAME : Abdulkabir Omeiza Abdulmalik')
print ('E-MAIL: abdulmaleekabdulkabir2017@gmail.com')
print ('LANGUAGE USED: python')
print ('BIOSTACK: Data analytics')
print ('SLACK USERNAME: @kaybee')
